# Site settings
title: "Bo Meyering - Portfolio"
email: "bomeyering@mailbox.org"
description: "A one pager to hold my CV and portfolio" # this means to ignore newlines until "baseurl:"
baseurl: "/root" # the subpath of your site, e.g. /blog/
url: "https://wwww.bomeyering.me" # the base hostname & protocol for your site

linkedin_username: bo-meyering-37955b139
github_username: BoMeyering

# Build settings
markdown: kramdown
